TUGAS TEKS PROCESSING REGULAR EXPRESSION

Di susun oleh:

Tabrizzi Aqlia — 25031554008
Citra Fanysa — 25031554015

In [ ]:
import re

**1**. **Ekstraksi ID Transaksi**

In [ ]:
text = "Pembayaran untuk pesanan #INV-2026-08912 telah berhasil diverifikasi pada pukul 14.30 WIB."
pattern = r"#(INV-\d{4}-\d+)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['INV-2026-08912']


Penjelasan : cari tanda pagar #, lalu setelah itu harus ada tulisan "INV-", lalu 4 angka (\d{4}), lalu strip, lalu angka lagi sebanyak apapun (\d+). Karena ada tanda kurung () di sekeliling "INV-\d{4}-\d+", Python cuma mengambil apa yang ada di dalam kurung itu, tanda pagarnya sendiri dibuang.

**2**. **Ekstraksi Nominal Harga (Rupiah)**

In [ ]:
text = "Total belanjaan Anda adalah Rp 450.000 dengan diskon promo sebesar Rp 50.000."
pattern = r"Rp\s?[\d.]+"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['Rp 450.000', 'Rp 50.000.']


Penjelasan : cari kata "Rp", boleh diikuti satu spasi atau tidak sama sekali (\s?), lalu setelah itu ambil sebanyak mungkin karakter yang berupa angka atau titik ([\d.]+).

Titik di sini dianggap "karakter yang boleh diambil" tanpa peduli itu titik pemisah ribuan atau titik tanda baca akhir kalimat. Makanya elemen kedua hasilnya jadi 'Rp 50.000.' (ada titik nyantol di ujung) — karena kalimat itu memang diakhiri titik tepat setelah angka terakhir.

**3**. **Masking Nomor Kartu Kredit**

In [ ]:
text = "Transaksi menggunakan kartu kredit 4532-1234-5678-9012 telah disetujui."
pattern = r"(\d{4})-(\d{4})-(\d{4})-(\d{4})"

masked = re.sub(pattern, r"XXXX-XXXX-XXXX-\4", text)
print("Hasil:", masked)

Hasil: Transaksi menggunakan kartu kredit XXXX-XXXX-XXXX-9012 telah disetujui.


Penjelasan :  
Nomor kartu dipecah jadi 4 kelompok 4-digit terpisah, masing-masing dibungkus kurung jadi grup 1, 2, 3, 4. Lalu dipakai re.sub dengan teks pengganti XXXX-XXXX-XXXX-\4.

\4 artinya "pakai lagi isi grup ke-4 yang tadi ditangkap". Jadi 3 kelompok pertama diganti paksa jadi "XXXX", tapi kelompok ke-4 (4 digit terakhir kartu) tetap dikembalikan apa adanya. Ini teknik standar untuk masking data sensitif — cukup tampilkan 4 digit terakhir saja.

**4**. **Validasi Kode Promo/Voucher**

In [ ]:
text = "Gunakan kode promo HEMAT50K atau DISKON100 untuk mendapatkan potongan harga."
pattern = r"\b[A-Z]+\d+[A-Z]*\b"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['HEMAT50K', 'DISKON100']


Penjelasan : \b artinya batas kata (jadi tidak nyangkut di tengah kata lain). Isinya: huruf besar satu atau lebih ([A-Z]+), lalu angka satu atau lebih (\d+), lalu opsional huruf besar lagi di belakang ([A-Z]*, boleh nol kali). Pola ini pas untuk kode promo yang biasanya "HURUF+ANGKA" atau "HURUF+ANGKA+HURUF".

**5**. **Identifikasi Metode Pembayaran (E-Wallet/Bank)**

In [ ]:
text = "Metode pembayaran yang dipilih: Transfer Bank BCA (VA: 88012345678)."
pattern = r"(Transfer Bank \w+|OVO|GoPay|DANA|ShopeePay)|VA:\s*(\d+)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: [('Transfer Bank BCA', ''), ('', '88012345678')]


Penjelasan :
Ini pattern dengan dua "kemungkinan besar" dipisah tanda | di level paling luar: kemungkinan pertama cocokkan nama metode bayar (Transfer Bank + nama banknya, atau nama e-wallet), kemungkinan kedua cocokkan angka Virtual Account setelah "VA:".

karena dua kemungkinan itu masing-masing punya kurungnya sendiri (grup 1 dan grup 2), setiap kali satu kemungkinan yang cocok, grup yang lain otomatis kosong. Makanya hasilnya berupa pasangan (tuple) dengan string kosong.

**6**. **Ekstraksi Kode SKU Produk**

In [ ]:
text = "Produk Sepatu Lari Kategori A [SKU: SHO-RUN-2026-BLK] tersisa 3 unit."
pattern = r"\[SKU:\s*([\w-]+)\]"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['SHO-RUN-2026-BLK']


Penjelasan : Tanda kurung siku [ dan ] di pattern ini bukan berarti "character class" seperti biasanya — karena di-escape pakai backslash (\[ dan \]), artinya cari tanda kurung siku beneran sebagai teks literal. Isinya: literal "SKU:", spasi opsional, lalu ambil kombinasi huruf/angka/underscore/strip ([\w-]+) sampai ketemu ].

**7**. **Deteksi Persentase Diskon**

In [ ]:
text = "Dapatkan diskon hingga 70% untuk produk kecantikan dan diskon ekstra 5% bagi member."
pattern = r"\d+%"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['70%', '5%']


Penjelasan : Paling sederhana di antara semua: cari angka (\d+) yang langsung diikuti tanda persen. Karena ada dua angka-persen di kalimat, keduanya ketemu.

 **8. Ekstraksi Dimensi Produk**

In [ ]:
text = "Ukuran paket: 30x20x15 cm dengan berat total 1.5 kg."
pattern = r"\d+x\d+x\d+\s?cm"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['30x20x15 cm']


Penjelasan : Cari tiga angka yang dipisah huruf "x" (panjang x lebar x tinggi), lalu spasi opsional, lalu literal "cm". Hanya cocok dengan bagian dimensi, bukan berat 1.5 kg-nya (karena "1.5" tidak berpola angka-x-angka-x-angka).$0

**9**. **Deteksi Berat Produk**

In [ ]:
text = "Berat bersih item ini adalah 500gr, sedangkan berat packing sekitar 0.75kg."
pattern = r"\d+(?:\.\d+)?\s?(?:gr|kg)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['500gr', '0.75kg']


Penjelasan : Angka bulat, lalu opsional bagian desimal ((?:\.\d+)? — tanda kurung dengan ?: di depan artinya "kelompok ini boleh ada boleh tidak, dan tidak perlu ditangkap sebagai grup terpisah"), lalu spasi opsional, lalu satuan "gr" atau "kg". Karena desimalnya opsional, pattern ini cocok baik untuk "500gr" (bulat) maupun "0.75kg" (desimal).

**10**. **Parsing Varian Warna dan Ukuran**

In [ ]:
text = "Kaos Polos Cotton 30s - Warna: Merah Cabai - Size: XL."
pattern = r"Warna:\s*([\w\s]+?)\s*-\s*Size:\s*(\w+)"

m = re.search(pattern, text)
print("Warna :", m.group(1))
print("Size  :", m.group(2))

Warna : Merah Cabai
Size  : XL


Penjelasan :
Dipakai re.search (cari satu match pertama saja, beda dari re.findall yang cari semua) karena hasilnya mau diambil per-grup pakai .group(1) dan .group(2).

Grup 1: teks setelah "Warna:" sampai ketemu " - Size:" — pakai tanda +? (lazy) supaya berhenti secepat mungkin, tidak "kebablasan" mengambil terlalu banyak. Grup 2: kata setelah "Size:".

**11**. **Ekstraksi Nomor Resi Pengiriman**

In [ ]:
text = "Paket Anda telah dikirim via JNE dengan no resi JNE102938475661."
pattern = r"\b[A-Z]{2,5}\d{8,}\b"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['JNE102938475661']


Penjelasan :
Cari 2 sampai 5 huruf besar berturut-turut (kode ekspedisi), langsung disambung minimal 8 digit angka. Karena "JNE102938475661" ditulis tanpa spasi antara huruf dan angka, semuanya ketangkap sebagai satu blok utuh.

**12**. **Deteksi Kode Pos Indonesia**

In [ ]:
text = "Alamat tujuan pengiriman: Jl. Mawar No. 12, Jakarta Selatan, 12410."
pattern = r"\b\d{5}\b"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['12410']


Penejlasan :
Cari tepat 5 digit angka, diapit batas kata di kedua sisi. Ini penting: kalimat itu juga ada angka "12" (dari "No. 12"), tapi karena cuma 2 digit, tidak akan cocok dengan \d{5} yang butuh persis 5 digit.

**13**. **Sanitasi Nomor Telepon Kurir/Pelanggan**

In [ ]:
text = "Hubungi kurir di 0812-3456-7890 atau +6281298765432 jika kendala."
pattern = r"(?:\+62|0)\d{2,4}(?:-?\d{3,4}){2,3}"

ditemukan = re.findall(pattern, text)
disensor = re.sub(pattern, "[NOMOR_DISENSOR]", text)
print("Ditemukan:", ditemukan)
print("Disensor :", disensor)

Ditemukan: ['0812-3456-7890', '+6281298765432']
Disensor : Hubungi kurir di [NOMOR_DISENSOR] atau [NOMOR_DISENSOR] jika kendala.


Penjelasan :
Nomor telepon Indonesia bisa diawali "0" atau "+62" — dua kemungkinan ini ditulis dalam (?:\+62|0). Setelah itu, 2-4 digit, lalu diikuti pola berulang "strip opsional + 3-4 digit" sebanyak 2 sampai 3 kali. Pattern ini cukup fleksibel menangani dua gaya penulisan sekaligus: yang pakai strip ("0812-3456-7890") dan yang tidak ("+6281298765432").

Setelah ditemukan, re.sub mengganti semua nomor yang ketemu jadi tulisan "[NOMOR_DISENSOR]" — teknik umum untuk menyembunyikan data pribadi di log atau tampilan publik.

**14**. **Ekstraksi Nama Kurir/Ekspedisi**

In [ ]:
text = "Pengiriman menggunakan opsi SiCepat REG (Estimasi 2-3 hari)."
pattern = r"\b(JNE|SiCepat|J&T|AnterAja|Ninja Express|Pos Indonesia|Wahana|Lion Parcel)\b(?:\s+\w+)?"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['SiCepat']


Penjelasna :
Daftar nama ekspedisi resmi ditulis sebagai alternasi (dipisah |) di dalam satu grup. Di belakangnya ada (?:\s+\w+)? — artinya "boleh diikuti satu kata tambahan setelah spasi, atau tidak sama sekali" — ini untuk menangkap layanan tambahan seperti "REG", "YES", "Express" kalau ada. Di kalimat ini kebetulan yang tertangkap cuma nama kurirnya.

**15**. P**arsing Estimasi Waktu Pengiriman**

In [ ]:
text = "Estimasi barang sampai ke lokasi tujuan adalah 2-4 hari kerja."
pattern = r"\d+-\d+\s?hari\s?kerja"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['2-4 hari kerja']


Penjelasan :
Angka, strip, angka lagi (rentang hari), lalu kata "hari" dan "kerja" dengan spasi opsional di antaranya. Cocok persis dengan susunan "2-4 hari kerja".

**16**. **Validasi Email Pelanggan**

In [ ]:
text = "Konfirmasi pesanan telah dikirim ke email pembeli: user_123@gmail.com."
pattern = r"[\w.+-]+@[\w-]+\.[a-zA-Z]{2,}"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['user_123@gmail.com']


Penjelasan :
Bagian sebelum "@": huruf/angka/underscore/titik/plus/strip ([\w.+-]+) — cukup umum untuk menangkap kebanyakan format email. Setelah "@": nama domain ([\w-]+), lalu titik literal, lalu ekstensi domain minimal 2 huruf ([a-zA-Z]{2,}, misal "com", "co.id" — tapi untuk domain dua-tingkat seperti "co.id" pattern ini cuma menangkap sampai satu titik saja).

**17**.** Ekstraksi Username Sosial Media**

In [ ]:
text = "Follow Instagram kami di @tokopediaseru dan TikTok @tokopedia_official."
pattern = r"@\w+"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['@tokopediaseru', '@tokopedia_official']


Penjekasan :
Tanda "@" diikuti kombinasi huruf/angka/underscore. Karena underscore termasuk dalam \w, "tokopedia_official" ikut tertangkap utuh, tidak terpotong di underscore-nya.

**18**. **Filter Kata Kasar/Spam di Ulasan**

In [ ]:
text = "Barang jelek banget, penipu ini seller ajg penipuan."
bad_words = ["ajg", "anjing", "kontol", "goblok", "penipu", "tolol", "bangsat"]
pattern = r"\b(" + "|".join(bad_words) + r")\w*\b"

ditemukan = re.findall(pattern, text, flags=re.IGNORECASE)
disensor = re.sub(pattern, lambda m: "*" * len(m.group()), text, flags=re.IGNORECASE)
print("Ditemukan:", ditemukan)
print("Disensor :", disensor)

Ditemukan: ['penipu', 'ajg', 'penipu']
Disensor : Barang jelek banget, ****** ini seller *** ********.


Penjelasan :
Pattern-nya tidak ditulis manual, tapi dirakit pakai kode: gabungkan semua kata di bad_words dengan tanda | di antaranya, lalu tambahkan \w* di belakang supaya imbuhan ikut tertangkap juga (misalnya "penipu" jadi tetap kena walau di teks ditulis "penipuan").

Untuk menyensor, dipakai re.sub dengan fungsi, bukan teks tetap:lambda m: "*" * len(m.group())
  yang dimana, setiap kata yang ketemu diganti bintang sebanyak panjang katanya sendiri — jadi jumlah bintangnya menyesuaikan, bukan jumlah tetap.

flags=re.IGNORECASE membuat pencarian tidak peduli huruf besar/kecil.

**19**. **Deteksi URL/Link Luar yang Dilarang di Chat**

In [ ]:
text = "Silakan transaksi langsung di website kami www.tokoku-murah.com ya kak."
pattern = r"(?:https?://\S+|www\.\S+)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['www.tokoku-murah.com']


Penejalasan :
Dua kemungkinan format URL: yang diawali "http://" atau "https://" (s? bikin huruf s opsional), atau yang diawali "www." Titik pada "www." di-escape supaya jadi titik literal (kalau tidak di-escape, titik di regex artinya "karakter apa saja").

**20**. **Ekstraksi Mention ID Pelanggan**

In [ ]:
text = "Customer Support membalas tiket pertanyaan dari customer ID: CUST-9921."
pattern = r"CUST-\d+"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['CUST-9921']


Penjelasan : Paling sederhana: literal "CUST-" diikuti angka.

**21**. **Ekstraksi Nilai Rating**

In [ ]:
text = "Produk ini mendapatkan ulasan 4.8 dari 5 bintang berdasarkan 250 pembeli."
pattern = r"\d+(?:\.\d+)?\s?dari\s?5\s?bintang"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['4.8 dari 5 bintang']


Penejelasan :
Angka dengan desimal opsional, lalu kata "dari", angka "5", dan kata "bintang" — semua dengan spasi opsional di antaranya. Pattern ini cukup spesifik: dia mengharuskan angka "5" persis (bukan sembarang angka), jadi cuma pas untuk rating skala 5 bintang.

**22**. **Deteksi Hashtag Promosi**

In [ ]:
text = "Beli baju baru di promo #FlashSale99 dan #BajuMurah sekarang!"
pattern = r"#\w+"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['#FlashSale99', '#BajuMurah']


Penejelasan :
Sama konsepnya seperti nomor 17 (username), tapi pakai tanda pagar bukan "@".

**23**. **Menghapus Tag HTML dari Deskripsi Produk**

In [ ]:
text = "<p>Bahan <b>Katun Premium</b> adem dan nyaman.</p>"
pattern = r"<[^>]+>"

bersih = re.sub(pattern, "", text)
print("Hasil:", bersih)

Hasil: Bahan Katun Premium adem dan nyaman.


Penjelasan :
Cari apapun yang diawali < dan diakhiri >, dengan syarat isi di dalamnya bukan tanda > ([^>] artinya "bukan karakter ini"). Ini trik praktis untuk membuang semua tag HTML tanpa perlu library parser HTML khusus. re.sub mengganti semua tag yang ketemu jadi string kosong (dihapus total).

**24**. **Ekstraksi Tanggal Ulasan**

In [ ]:
text = "Ulasan ditulis oleh Ahmad pada tanggal 12/08/2026."
pattern = r"\d{2}/\d{2}/\d{4}"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['12/08/2026']


Penjelasan :
Format tanggal DD/MM/YYYY secara literal: 2 digit, garis miring, 2 digit, garis miring, 4 digit. Catatan: pattern ini tidak memvalidasi apakah bulannya masuk akal (01-12) atau tidak — dia cuma cocok berdasarkan jumlah digit saja.

**25**. **Deteksi Sentimen Kata Kunci Positif**

In [ ]:
text = "Pengiriman sangat cepat, kualitas ori dan seller ramah!"
positive_words = ["cepat", "ori", "ramah", "bagus", "puas", "recommended", "mantap"]
pattern = r"\b(" + "|".join(positive_words) + r")\b"

hasil = re.findall(pattern, text, flags=re.IGNORECASE)
print("Hasil:", hasil)

Hasil: ['cepat', 'ori', 'ramah']


Penjelasan :
Sama teknik dengan nomor 18, tapi untuk daftar kata positif, tanpa \w* tambahan di belakang (jadi harus cocok kata utuh, tidak termasuk imbuhan).

**26**. **Ekstraksi Alamat IP Pengguna**

In [ ]:
text = "Aktivitas login mencurigakan terdeteksi dari IP 192.168.1.105 pada lokasi Jakarta."
pattern = r"\b(?:\d{1,3}\.){3}\d{1,3}\b"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['192.168.1.105']


Penjelasan :
Alamat IP terdiri dari 4 kelompok angka dipisah titik. Pattern-nya: kelompok "1-3 digit diikuti titik" yang diulang tepat 3 kali ({3}), lalu ditutup satu kelompok terakhir tanpa titik di belakangnya.

kita bisa lihat , bahwa pattern ini tidak mengecek apakah angkanya masuk rentang 0-255 (rentang IP yang valid). Jadi kalau ada teks aneh seperti "999.999.999.999", pattern ini tetap akan menganggapnya cocok walau itu bukan alamat IP yang benar-benar valid. Untuk kebutuhan sekadar mengambil teks berformat IP, ini cukup; untuk validasi ketat, perlu pattern tambahan.

**27**. **Parsing Log Waktu Server**

In [ ]:
text = "[2026-09-02 08:30:15] ERROR: Gagal memproses transaksi ID 992."
pattern = r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['2026-09-02 08:30:15']


Penjelasan : Kurung siku literal (di-escape), berisi grup tanggal format ISO (YYYY-MM-DD) diikuti spasi dan jam (HH:MM:SS). Formatnya baku, cocok untuk membaca timestamp dari file log.

**28**. **Ekstraksi HTTP Status Code**

In [ ]:
text = "API Payment Gateway merespons dengan status POST /checkout HTTP/1.1 200 OK."
pattern = r"HTTP/\d\.\d\"?\s(\d{3})"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['200']


Penjelasan :
Cari literal "HTTP/", lalu versi protokol (satu digit, titik, satu digit — misal "1.1"), lalu tanda kutip opsional (\"?, untuk jaga-jaga kalau format log-nya pakai kutip), lalu spasi, lalu grup 3 digit kode status HTTP.

**29**. **Deteksi Percobaan SQL Injection di Kolom Pencarian**

In [ ]:
text = "User mencari keyword: baju pria' OR '1'='1"
pattern = r"(?i)('\s*(?:or|and)\s*'?\w+'?\s*=\s*'?\w+'?|--|;\s*--|\bunion\b|\bselect\b|\bdrop\b)"

terdeteksi = bool(re.search(pattern, text))
match = re.findall(pattern, text)
print("Terdeteksi:", terdeteksi)
print("Match     :", match)

Terdeteksi: True
Match     : ["' OR '1'='1"]


Penjelasan :
(?i) di awal artinya "abaikan besar/kecil huruf untuk seluruh pattern ini" (sama efeknya dengan flags=re.IGNORECASE, tapi ditulis langsung di dalam pattern). Setelah itu ada beberapa kemungkinan pola dipisah |, masing-masing adalah ciri khas serangan SQL injection:

kutip diikuti "OR"/"AND" lalu perbandingan nilai ('...OR...=...') — pola klasik "bypass login"
-- atau ;-- — tanda komentar SQL, dipakai untuk "mematikan" sisa query
kata kunci berbahaya seperti union, select, drop

**30**. **Parsing Slug URL Produk**

In [ ]:
text = "Halaman diakses: https://tokopedia.com/p/sepatu-sneakers-pria-white-edition"
pattern = r"/p/([\w-]+)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['sepatu-sneakers-pria-white-edition']


Penjelasan :
Cari literal "/p/" (pola umum di URL produk e-commerce), lalu tangkap semua huruf/angka/ underscore/strip setelahnya sebagai grup — ini yang disebut "slug", biasanya nama produk yang sudah diubah jadi format URL-friendly.

**31**. **Deteksi Batas Waktu Bayar (Countdown/Timer)**

In [ ]:
text = "Selesaikan pembayaran Anda dalam 01:45:30 sebelum pesanan dibatalkan."
pattern = r"\b\d{2}:\d{2}:\d{2}\b"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['01:45:30']


Penjelasan :
Format jam:menit:detik, masing-masing tepat 2 digit, dipisah titik dua, diapit batas kata.

**32**. **Parsing Jumlah Stok (Inventory Quantity)**

In [ ]:
text = "Stok Gudang A: 150 pcs | Stok Gudang B: 20 pcs."
pattern = r"Stok\s+([\w\s]+?):\s*(\d+)\s*pcs"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: [('Gudang A', '150'), ('Gudang B', '20')]


Penjelasan :
Grup 1: nama gudang, diambil pakai +? (lazy, berhenti secepat mungkin) supaya tidak "kebablasan" mengambil teks sampai titik dua berikutnya. Grup 2: jumlah stoknya (angka).

Karena ada 2 grup capture dan dipakai findall, hasilnya berupa list of tuple — satu tuple per gudang yang ditemukan.

**33**. **Ekstraksi Kode Rak/Lokasi Bin Gudang**

In [ ]:
text = "Ambil barang di Lokasi Rak: RAK-A3-BAY12."
pattern = r"RAK-[\w\d]+-[\w\d]+"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['RAK-A3-BAY12']


Penjelasan :
Literal "RAK-", lalu segmen alfanumerik pertama ("A3"), strip, segmen alfanumerik kedua ("BAY12"). Struktur kode gudang yang khas: kategori-baris-posisi.

**34**.**Deteksi Status Pesanan**

In [ ]:
text = "Pesanan #1092 berubah status dari [MENUNGGU_PAYMENT] menjadi [DISELESAIKAN]."
pattern = r"\[([A-Z_]+)\]"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['MENUNGGU_PAYMENT', 'DISELESAIKAN']


Penjelasan :
Tangkap teks huruf besar dan underscore yang diapit kurung siku literal. Karena findall mengambil semua kecocokan (bukan cuma yang pertama), dua status berbeda di kalimat yang sama berhasil ditangkap sekaligus.

**35**.**Parsing Berat Total & Biaya Ongkir**

In [ ]:
text = "Berat Total: 3kg - Biaya Pengiriman: Rp 27.000."
pattern = r"Berat Total:\s*(\d+(?:\.\d+)?kg)\s*-\s*Biaya Pengiriman:\s*(Rp\s?[\d.]+)"

m = re.search(pattern, text)
print("Berat Total     :", m.group(1))
print("Biaya Pengiriman:", m.group(2))

Berat Total     : 3kg
Biaya Pengiriman: Rp 27.000.


Penjelasan :
Dua grup dalam satu pattern panjang: grup 1 tangkap berat (angka + opsional desimal + "kg" langsung menyatu, beda dari nomor 9 yang memisah angka dan satuan), grup 2 tangkap nominal biaya pengiriman — memakai pola yang sama seperti nomor 2 (Rp\s?[\d.]+), jadi titik di akhir kalimat ikut tertangkap juga di sini.

**36**.**Membersihkan Multiple White Space pada Deskripsi**

In [ ]:
text = "Baju   kaos pria    lengan panjang."
pattern = r"\s{2,}"

bersih = re.sub(pattern, " ", text).strip()
print("Sebelum:", repr(text))
print("Sesudah:", repr(bersih))

Sebelum: 'Baju   kaos pria    lengan panjang.'
Sesudah: 'Baju kaos pria lengan panjang.'


Penjelasan :
Dimana pada 2 spasi/whitespace atau lebih berturut-turut. re.sub mengganti semua kemunculan itu jadi satu spasi tunggal, lalu .strip() di akhir membuang spasi sisa di awal/akhir kalimat (kalau ada).

**37**. **Ekstraksi Angka dari Format Campuran (Angka & Teks)**

In [ ]:
text = "Paket berisi 12pcs piring, 5pcs gelas, dan 1set sendok."
pattern = r"(\d+)(pcs|set)"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: [('12', 'pcs'), ('5', 'pcs'), ('1', 'set')]


Penjelasan :
Dua grup terpisah tapi saling menempel (tanpa spasi di antaranya di pattern): angka, lalu langsung satuannya ("pcs" atau "set"). Karena teks aslinya memang menulis satuan langsung nempel ke angka ("12pcs", bukan "12 pcs"), pattern ini cocok.

**38**.**Deteksi Penggunaan EMOTICON/EMOJI Unicode**

In [ ]:
text = "Barangnya bagus banget kak! \U0001F44D\U0001F525 Recommended seller! \u2764\uFE0F"
pattern = r"[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF]"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: ['👍', '🔥', '❤']


Penjelasan :
Ini bukan mendeteksi emoji berdasarkan "tampilannya", tapi berdasarkan rentang kode Unicode resmi tempat emoji didefinisikan. Ada 3 rentang digabung dalam satu character class [...]:

1. \U0001F300 sampai \U0001FAFF — blok simbol & piktograf (mencakup 👍 dan 🔥)
2. \U00002600 sampai \U000027BF — blok simbol lain-lain & dingbat
3. \U0001F1E6 sampai \U0001F1FF — blok huruf regional (dipakai untuk bendera negara)

**39**. **Parsing Nama dan Nilai Atribut Spesifikasi (JSON-like text)**

In [ ]:
text = "Spesifikasi: [RAM: 8GB], [Storage: 256GB], [Baterai: 5000mAh]"
pattern = r"\[(\w+):\s*([\w\d]+)\]"

hasil = re.findall(pattern, text)
print("Hasil:", hasil)

Hasil: [('RAM', '8GB'), ('Storage', '256GB'), ('Baterai', '5000mAh')]


Penjelasan :
Mirip konsep dengan nomor 34, tapi kali ini ada dua grup: grup 1 nama atributnya (sebelum titik dua), grup 2 nilainya (setelah titik dua). Karena tiga blok "[Nama: Nilai]" ada di teks, findall mengembalikan tiga tuple sekaligus.

**40**.**(Bonus) Normalisasi Kata Baku Singkatan Chat**

In [ ]:
text = "brg sdh smp dgn slmt, tq seller"
kamus = {
    "brg": "barang", "sdh": "sudah", "smp": "sampai", "dgn": "dengan",
    "slmt": "selamat", "tq": "terima kasih", "yg": "yang", "gk": "tidak",
    "ga": "tidak", "aja": "saja", "bgt": "banget", "utk": "untuk",
    "dr": "dari", "krn": "karena", "jd": "jadi", "dpt": "dapat",
}
pattern = r"\b\w+\b"

def ganti(m):
    kata = m.group(0)
    return kamus.get(kata.lower(), kata)

hasil = re.sub(pattern, ganti, text)
print("Sebelum:", text)
print("Sesudah:", hasil)

Sebelum: brg sdh smp dgn slmt, tq seller
Sesudah: barang sudah sampai dengan selamat, terima kasih seller


Penjelasan :
1. Untuk setiap kata yang match pattern (yaitu semua kata dalam kalimat, karena \b\w+\b sangat umum), Python memanggil fungsi ganti.
2. Di dalam fungsi, m.group(0) mengambil kata asli yang sedang diproses.
3. kamus.get(kata.lower(), kata) mengecek: kalau kata itu (versi huruf kecil) ada di dalam kamus singkatan, kembalikan bentuk bakunya. Kalau tidak ada di kamus, kembalikan kata aslinya tanpa perubahan (ini fungsi parameter kedua pada .get() — nilai default kalau key tidak ditemukan).
4. Hasil dari fungsi ini otomatis dipakai re.sub sebagai pengganti tiap kata.